# reference: https://docs.confluent.io/current/installation/docker/docs/config-reference.html
#
# docker-compose -f .\kafka-local.yml up
# 

version: '3'
services:

  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.1.0
    container_name: zookeeper-1
    ports:
      - "3601:22181"
    volumes:
      - data_zookeeper_1:/var/lib/zookeeper
      - data_zookeeper_1:/etc/zookeeper/secrets
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:22888:23888;zookeeper-3:22888:23888
     
    networks:
      - kafka_network

  zookeeper-2:
    image: confluentinc/cp-zookeeper:5.1.0
    container_name: zookeeper-2
    ports:
      - "3602:22181"
    volumes:
      - data_zookeeper_2:/var/lib/zookeeper
      - data_zookeeper_2:/etc/zookeeper/secrets
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:22888:23888;zookeeper-3:22888:23888

    networks:
      - kafka_network

  zookeeper-3:
    image: confluentinc/cp-zookeeper:5.1.0
    container_name: zookeeper-3
    ports:
      - "3603:22181"
    volumes:
      - data_zookeeper_3:/var/lib/zookeeper
      - data_zookeeper_3:/etc/zookeeper/secrets
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:22888:23888;zookeeper-3:22888:23888
    networks:
      - kafka_network

  kafka-1:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "4601:4601"
    volumes:
      - data_kafka_1:/var/lib/kafka/data
      - data_kafka_1:/var/lib/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:22181,zookeeper-3:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://FXWVRN2:4601
      KAFKA_LOG_DIR: /var/lib/kafka/data
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 30000
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 48
      KAFKA_OFFSETS_RETENTION_MINUTES: 14400
      KAFKA_MESSAGE_MAX_BYTES: 25000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 25485760
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - kafka_network

  kafka-2:
    image: confluentinc/cp-kafka:5.1.0      
    container_name: kafka-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "4602:4602"
    volumes:
      - data_kafka_2:/var/lib/kafka/data
      - data_kafka_2:/var/lib/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:22181,zookeeper-3:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://FXWVRN2:4602
      KAFKA_LOG_DIR: /var/lib/kafka/data
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 30000
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 48
      KAFKA_OFFSETS_RETENTION_MINUTES: 14400
      KAFKA_MESSAGE_MAX_BYTES: 25000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 25485760
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - kafka_network

  kafka-3:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka-3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "4603:4603"
    volumes:
      - data_kafka_3:/var/lib/kafka/data
      - data_kafka_3:/var/lib/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:22181,zookeeper-3:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://FXWVRN2:4603
      KAFKA_LOG_DIR: /var/lib/kafka/data
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 30000
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 48
      KAFKA_OFFSETS_RETENTION_MINUTES: 14400
      KAFKA_MESSAGE_MAX_BYTES: 25000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 25485760
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - kafka_network
  
# https://github.com/confluentinc/schema-registry/blob/93c0297b11ccc755e232ba77de87f88819ee3958/core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
  schema-1:
    image: confluentinc/cp-schema-registry:5.1.0
    container_name: schema-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always
    ports:
      - "5601:5601"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:22181,zookeeper-2:22181,zookeeper-3:22181
      SCHEMA_REGISTRY_HOST_NAME: schema-1
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-1:5601'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
#      SCHEMA_REGISTRY_HOST: schema?
    networks:
      - kafka_network

  schema-2:
    image: confluentinc/cp-schema-registry:5.1.0
    container_name: schema-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always
    ports:
      - "5602:5602"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:22181,zookeeper-2:22181,zookeeper-3:22181
      SCHEMA_REGISTRY_HOST_NAME: schema-2
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-2:5602'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - kafka_network

  schema-3:
    image: confluentinc/cp-schema-registry:5.1.0
    container_name: schema-3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always
    ports:
      - "5603:5603"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:22181,zookeeper-2:22181,zookeeper-3:22181
      SCHEMA_REGISTRY_HOST_NAME: schema-3
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-3:5603'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - kafka_network

################################## below are not required for app to run ##########################################################
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.1.0
    container_name: kafka-rest
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-1
      - schema-2
      - schema-3
    restart: always
    ports:
      - "6601:6601"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:22181,zookeeper-3:22181
      KAFKA_REST_HOST_NAME: kafka-rest      
      KAFKA_REST_LISTENERS: http://0.0.0.0:6601
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-1:5601   
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://FXWVRN2:4601
    networks:
      - kafka_network

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    container_name: kafka-topics-ui
    depends_on:
      - kafka-rest
    ports:
    - "8601:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest:6601"
      PROXY: "true"
    networks:
      - kafka_network

  schema-registry-ui:
    image: landoop/schema-registry-ui:0.9.5 
    container_name: schema-registry-ui
    depends_on:
      - schema-1
      - schema-2
      - schema-3
    ports:
    - "7601:8000"
    environment:
      SCHEMAREGISTRY_URL: "http://schema-1:5601" 
      ALLOW_GLOBAL: 1 
      ALLOW_TRANSITIVE: 1
      ALLOW_DELETION: 1
      PROXY: "true"
    networks:
      - kafka_network
  
  zookeeper-api:
    image: elkozmon/zoonavigator-api:0.5.0
    container_name: zookeeper-api
    environment:
      API_HTTP_PORT: 9000
    restart: always
    networks:
      - kafka_network

  zookeeper-web:
    image: elkozmon/zoonavigator-web:0.5.0
    container_name: zookeeper-web
    ports:
    - "9601:9001"
    environment:
      WEB_HTTP_PORT: 9001 
      API_HOST: zookeeper-api
      API_PORT: 9000
    depends_on:
      - zookeeper-api
    restart: always
    networks:
      - kafka_network



networks:
  kafka_network:

volumes:
  data_kafka_1:
  data_kafka_2:
  data_kafka_3:
  data_zookeeper_1:
  data_zookeeper_2:
  data_zookeeper_3:
